"""added start and end to task table

Revision ID: 9dab8fb3b9da
Revises: 08ac1dc871d9
Create Date: 2019-10-26 00:40:08.896085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dab8fb3b9da'
down_revision = '08ac1dc871d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('end', sa.String(length=120), nullable=True))
    op.add_column('task', sa.Column('start', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_task_end'), 'task', ['end'], unique=True)
    op.create_index(op.f('ix_task_start'), 'task', ['start'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_start'), table_name='task')
    op.drop_index(op.f('ix_task_end'), table_name='task')
    op.drop_column('task', 'start')
    op.drop_column('task', 'end')
    # ### end Alembic commands ###
