"""Task nonunique

Revision ID: cb6963b31507
Revises: 9dab8fb3b9da
Create Date: 2019-10-26 17:31:17.878946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb6963b31507'
down_revision = '9dab8fb3b9da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_end', table_name='task')
    op.create_index(op.f('ix_task_end'), 'task', ['end'], unique=False)
    op.drop_index('ix_task_minutes', table_name='task')
    op.create_index(op.f('ix_task_minutes'), 'task', ['minutes'], unique=False)
    op.drop_index('ix_task_start', table_name='task')
    op.create_index(op.f('ix_task_start'), 'task', ['start'], unique=False)
    op.drop_index('ix_task_title', table_name='task')
    op.create_index(op.f('ix_task_title'), 'task', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_title'), table_name='task')
    op.create_index('ix_task_title', 'task', ['title'], unique=1)
    op.drop_index(op.f('ix_task_start'), table_name='task')
    op.create_index('ix_task_start', 'task', ['start'], unique=1)
    op.drop_index(op.f('ix_task_minutes'), table_name='task')
    op.create_index('ix_task_minutes', 'task', ['minutes'], unique=1)
    op.drop_index(op.f('ix_task_end'), table_name='task')
    op.create_index('ix_task_end', 'task', ['end'], unique=1)
    # ### end Alembic commands ###
